### PR TITLE
Fixes and Functors.jl compat

### PR DESCRIPTION
**Pull request by oschulz**

### CODE REVIEW

**Comment by oschulz** [comment]
@cscherrer need your review before I can merge this. :-)

**Review by cscherrer — APPROVED** [review]
Sorry I didn't get to this today. From a quick glance on my phone it looks like minor stuff so I've approved, let me know if you think it needs a closer review.

DistributionMeasures is basically all your code, I think we should just transfer it to you. What do you think?

**Comment by oschulz** [comment]
> DistributionMeasures is basically all your code, I think we should just transfer it to you. What do you think?

Sure, let's do it.

Longer term, we can probably restructure the way this (and many similar things) are handled, using the upcoming ["extensions"](https://pkgdocs.julialang.org/dev/creating-packages/#Conditional-loading-of-code-in-packages-(Extensions)) Pkg feature in Julia v1.9.

**Comment by oschulz** [comment]
Closes #19

**Pull request merged**
